Lambda-School-Labs/community-calendar-fe

src/graphql/events.query.js
Updated the events query to return events in order of descending start date.
=> events query by descending start time

src/components/event_fltr_btns/EvntFltrBtns.module.scss, src/components/featured/Featured.module.scss, src/components/featured/FeaturedCard.jsx, src/components/featured/FeaturedCarousel.jsx, src/pages/Home.jsx, src/styles/_carousel_overrides.scss, src/styles/index.scss
conditional statement to only render carousel when there are events on the selected dates
fixed duplicate items showing in carousel
=> Carousel fix

package-lock.json, package.json
=> updated version of react-hook-form

jest.config.js, package-lock.json, package.json, src/components/__tests__/Navbar.test.jsx, src/components/navbar/Navbar.jsx, src/utils/__tests__/getPosition.test.jsx, test-utils/setup-tests.js
Also set snapshot test for Navbar.jsx to "skip" while it is being worked on.
Added the window.navigator mock to the Navbar test file so the other tests for it would pass.
Changed @apollo/react-testing from regular dependency to dev dependency.
=> Fixed title hover text in NavBar.jsx

src/components/icons/ArrowIcon.jsx, src/components/icons/DropdownIcon.jsx, src/components/icons/Icons.module.scss, src/components/icons/SearchIcon.jsx, src/components/icons/index.js, src/components/navbar/Navbar.jsx, src/components/navbar/Navbar.module.scss, src/components/navbar/NavbarSearchBox.jsx, src/styles/_bulma_overrides.scss, src/styles/_global.scss, src/styles/_helper_classes.scss, src/styles/_mixins.scss
Navbar is now responsive and more closely matches the design spec.
=> made navbar responsive

src/components/__tests__/EventListCard.test.jsx, src/components/__tests__/FeaturedCard.test.jsx, src/components/__tests__/__snapshots__/EventListCard.test.jsx.snap, src/components/__tests__/__snapshots__/FeaturedCard.test.jsx.snap, src/components/events/EventListCard.jsx, src/components/events/styles/EventListCard.module.scss, src/pages/__tests__/EventView.test.jsx, test-utils/mock_data/test_event.js
Modified eventlistcard display of distance from user to match design spec
Wrote tests to indicate whether conditional rendering of neighborhood and distance from user works as expected
=> EventListCard matches design spec and is tested

src/components/event_forms/EventForm.jsx, src/components/event_forms/eventSchema.js, src/components/event_forms/styles/EventForm.module.scss, src/pages/CreateEventPage.jsx, src/pages/UpdateEventPage.jsx, src/pages/styles/EventFormPage.module.scss
Form validation works for basic form fields using `error` property of useForm hook and the `ErrorMessage` component from react-hook-form. Yup validation schema defined in `eventSchema.js`
Further work needs to be done to validate all non-standard form fields that are not managed by react-hook-form (date/time pickers, image upload, and tags)
=> Form validation

src/components/event_forms/EventForm.jsx
Fixes issue causing tags to not be removed when updating an event.
=> fixed issue when removing tags in update event form

src/components/distance-dropdown/DistanceDropdown.jsx, src/components/icons/DropdownIcon.jsx, src/components/icons/Icons.module.scss, src/components/navbar/Navbar.jsx, src/pages/EventView.jsx, src/pages/Home.jsx, src/pages/styles/EventView.module.scss, src/pages/styles/Home.module.scss, src/styles/_helper_classes.scss
Created a button for managing events on the Single Event Page.
=> added dropdown menu for managing events

src/components/event_forms/CreateEvent.jsx, src/components/event_forms/EventForm.jsx, src/components/events/EventListCard.jsx, src/components/featured/FeaturedCard.jsx, src/components/loading/Loading.module.scss, src/components/loading/LoadingDots.jsx, src/components/navbar/Navbar.jsx, src/pages/EventView.jsx, src/utils/filterByDistance.js
Adding geocoding to Create Event form to find the coordinates for an event.
=> Create event geolocation

src/components/events/DeleteEventModal.jsx, src/components/events/styles/DeleteEventModal.module.scss, src/pages/EventView.jsx
=> Delete event modal

src/components/featured/FeaturedCarousel.jsx, src/components/geocoder/Geocoder.jsx, src/components/navbar/Navbar.jsx, src/pages/EventView.jsx, src/pages/SearchResults.jsx
The location dropdown in the Navbar now closes when the user clicks outside of it. 
A user can search for multiple keywords at the same time by separating words with spaces.
Commented out "Hosted By" and "Attend" buttons on EventView.jsx.
Need a store the auth0.user.nickname and auth0.user.picture in db so they can be displayed on the EventView.
=> Update Location Dropdown and Search

src/components/events/EventListCard.jsx, src/pages/EventView.jsx
Added more specific time/date information on event view/cards.
Information is displayed differently depending if an event falls on one day or multiple days.
=> Events dates times

src/components/event_forms/EventForm.jsx, src/components/event_forms/eventSchema.js, src/graphql/events.mutation.js, src/graphql/events.query.js, src/graphql/localState.jsx, src/pages/EventView.jsx, test-utils/mock_data/test_event.js
also updated create event form
=> changed ticketType to ticketPrice 

src/components/event_forms/UpdateEvent.jsx, src/graphql/events.mutation.js
No longer creates new location when you update
Fixes issue #75
=> updateEvent mutation and form updates location

src/graphql/events.query.js, src/graphql/index.js, src/pages/Home.jsx
order the event list by start_ASC
make carousel static first 6 chronological events
=> modify homepage orderBy start_ASC and with static carousel

src/components/event_forms/EventForm.jsx, src/pages/SearchResults.jsx
Fixed a bug encountered when updating an event without an image.
=> Fix update event image

.babelrc, build-utils/webpack.common.js, package-lock.json, package.json, src/App.jsx, src/components/distance-dropdown/DistanceDropdown.jsx, src/components/event_forms/CreateEvent.jsx, src/components/event_forms/EventForm.jsx, src/components/event_forms/UpdateEvent.jsx, src/components/filters/FilterMenu.jsx, src/components/navbar/Navbar.jsx, src/components/user_profile/EditUserForm.jsx, src/graphql/index.js, src/pages/AboutUs.jsx, src/pages/Home.jsx, src/pages/UserProfilePage.jsx, src/styles/index.scss
Implemented code splitting with Webpack. Already reduced bundle size from 2.01 Mb to 1.74Mb.
=> Code splitting

src/App.jsx, src/utils/index.js, src/utils/protectedRoute.js
This feature brings the protective routes for create event and profile page. With this feature, the signed out user can not navigate to the pages that he is not authorized to.  User will will redirected to homepage if he tries to access the above mentioned routes.
=> Added protected routes for create event and profile page

src/components/event_forms/EventForm.jsx, src/components/event_forms/styles/EventForm.module.scss
- This feature adds validation and restricts the user from creating an event without uploading an image
- Fixes issue when a user previously created an event without an image upload the event list alignment would be thrown off.
=> Feature enforce img upload

src/components/event_forms/EventForm.jsx, src/components/event_forms/styles/EventForm.module.scss, src/graphql/events.query.js
This new feature is added to the calender on createEvent page. It adds a visual indicator on calendar dates that have scheduled events on them. In addition to that, the event organizer can click the date to get more details, like title, time and location, for the events planned for that particular date. This feature will especially be useful for event organizers to avoid time/location conflicts with other events happening in the community.
=> Visual indicator on create event calendar

src/components/event_forms/styles/EventForm.module.scss, src/components/search-results/SearchResults.jsx, src/styles/_variables.scss
This PR adds some styling changes to our already existing feature. The changes will make our home page look less cluttered. In addition, media queries are added on createEvent calendar making it responsive at mobile and tablet resolutions.
=> Styling changes on HomePage and CreateEventPage

src/components/event_forms/EventForm.jsx, src/components/event_forms/UpdateEventModal.jsx, src/components/event_forms/styles/UpdateEventModal.module.scss, src/components/event_forms/styles/UpdateEventModal.scss, src/components/events/DeleteEventModal.jsx, src/components/events/styles/DeleteEventModal.module.scss, src/pages/EventView.jsx, src/pages/styles/EventView.module.scss
Added a delete series modal and an update series modal to display whenever someone tries to delete/update an event that is part of a series. Also added text to show in event view if the event is part of a series.
Remove any items which are not applicable.
=> Series Modals

src/graphql/events.mutation.js, src/graphql/events.query.js, src/graphql/index.js, src/graphql/series.mutation.js
This PR adds graphQL queries for recurring events to confirm if the added event is part of a series or not. In addition, mutations to perform CRUD operations are also drafted. These mutations will facilitate to add events to a recurring series and those series can be edited or deleted 
with edit series and delete series mutations.
=> GraphQL queries and mutations for recurring events!
